#!/usr/bin/env python3
"""Compile LG TV blocklist source files into distributable formats.

Pure stdlib. Formats: plain domains, hosts (0.0.0.0), adblock (||x^).
strict = safe + strict-delta (+ zone anchors). Zones become apex lines in
domains/hosts outputs and ||zone^ in the adblock output.
"""
import argparse
import hashlib
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
LISTS = ROOT / "lists"
README = ROOT / "README.md"
# Where the published per-country lists live. Fork-specific: a fork that
# distributes its own lists must point this at its own repo, or the README's
# country links serve someone else's build.
RAW_BASE = "https://raw.githubusercontent.com/sink-await/lg-tv-blocklist-global/main"
README_BEGIN = "<!-- BEGIN COUNTRY LINKS (generated by scripts/build.py) -->"
README_END = "<!-- END COUNTRY LINKS -->"
# parse_src strips exactly one trailing dot (FQDN root) before matching, so
# anything still ending in "." here (e.g. "host..") is malformed.
HOSTNAME_RE = re.compile(r"^(?=.{1,253}$)[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)*$")
LG_SUFFIXES = ("lge.com", "lgappstv.com", "lgtvsdp.com", "lgtvcommon.com",
               "lgtviot.com", "lgthinq.com", "nextlgsdp.com", "lgsmartad.com",
               "lgsmartplatform.com", "lgeapi.com", "wiselg.com",
               "lgechannel.com", "adtvc.app", "adsdtvc.com",
               "lgunifiedsmart.com", "lggalleryplus.com", "lgsmartweb.com",
               "ueiwsp.com")

LICENSE_LINE = "# License: CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/)"

# Region cross-product. LG runs a per-country endpoint matrix, so one audited
# host implies the same host under every other country code. Tagging that entry
# [REGION-SCOPED] expands it across src/regions.txt at build time, which beats
# hand-writing ~50 lines per family and forgetting one when a family is found.
#
# The tag is explicit and never inferred from the hostname, because a
# two-letter first label does not mean "country": ad.lgappstv.com is an ad host
# on the store CDN, am./ig..lge.com are unknown services, su.lge.com is the OTA
# server. Expanding any of those would emit ~50 bogus store-CDN entries and
# could break the Content Store for everyone.
# A bare [REGION-SCOPED] expands to every code in regions.txt. Not every
# service exists in every market, though -- ibs.nextlgsdp.com (in-app billing)
# resolves in 20 of 49 -- so the tag takes an optional explicit subset,
# [REGION-SCOPED: ar at br ...], and generating a name that NXDOMAINs would
# violate this project's own live-domain rule (see docs/methodology.md).
# Deliberately loose: match any [REGION-SCOPED...] and validate the contents
# below, so a malformed tag is a hard error. A strict pattern would simply fail
# to match a typo, silently dropping that family's whole regional coverage.
REGION_TAG_RE = re.compile(r"\[REGION-SCOPED\b([^\]]*)\]")
REGION_CODE_RE = re.compile(r"^[a-z]{2}$")
REGIONS_FILE = "regions.txt"
# Datacentre clusters: eic=Europe, aic=Americas, kic=Korea. Confirmed by the
# regional CNAME targets (de.* -> eic-*, us.* -> aic-*) seen in CERTIFICATES.md.
CLUSTER_PREFIXES = ("eic", "aic", "kic")
CLUSTER_RE = re.compile(r"^(eic|aic|kic)([.-])(.+)$")
GENERATED_NOTE = (
    "# Note: {n} of these are generated region endpoints ({codes} country codes x "
    "{fams} host families). Generated entries are DNS-verified only -- they "
    "resolve to that region's LG infrastructure -- not traffic-observed. The "
    "audited entries are annotated in src/."
)


def now_utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def parse_src(filename: str) -> list[str]:
    """Return sorted, validated hostnames from an annotated src file.

    Raises ValueError (with line numbers) on duplicate, malformed, or
    non-LG-related hostnames.
    """
    path = SRC / filename
    seen: dict[str, int] = {}
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        host = line.lower()
        if host.endswith("."):
            host = host[:-1]
        if not HOSTNAME_RE.match(host):
            raise ValueError(f"{filename}:{lineno}: malformed hostname: {line!r}")
        if not any(host == suffix or host.endswith("." + suffix) for suffix in LG_SUFFIXES):
            raise ValueError(f"{filename}:{lineno}: not an LG family hostname: {host}")
        if host in seen:
            raise ValueError(f"{filename}:{lineno}: duplicate of {host} (first at line {seen[host]})")
        seen[host] = lineno
    return sorted(seen)


def parse_regions() -> dict[str, str]:
    """Return {country code: display name} from src/regions.txt, sorted by code.

    Optional by design: with no regions.txt the build is exactly the
    hand-audited lists, so the cross-product can be dropped without
    touching anything else. The display name is the entry's inline comment,
    used only for the README country table.
    """
    path = SRC / REGIONS_FILE
    if not path.is_file():
        return {}
    seen: dict[str, int] = {}
    names: dict[str, str] = {}
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        code, _, comment = raw.partition("#")
        code = code.strip().lower()
        if not code:
            continue
        if not REGION_CODE_RE.match(code):
            raise ValueError(
                f"{REGIONS_FILE}:{lineno}: not a two-letter country code: {code!r}")
        if code in seen:
            raise ValueError(
                f"{REGIONS_FILE}:{lineno}: duplicate of {code} (first at line {seen[code]})")
        seen[code] = lineno
        names[code] = comment.split("—")[0].strip() or code.upper()
    return {code: names[code] for code in sorted(names)}


def region_patterns(filename: str) -> dict[str, tuple[str, ...] | None]:
    """Return {suffix: explicit code subset or None} for [REGION-SCOPED] entries.

    None means "every code in regions.txt". A subset is used where the service
    does not exist in every market. Raises ValueError if a tagged entry has no
    two-letter first label to substitute -- that tag is then a typo, and
    silently ignoring it would quietly drop a family's regional coverage.
    """
    patterns: dict[str, tuple[str, ...] | None] = {}
    for lineno, raw in enumerate(
            (SRC / filename).read_text(encoding="utf-8").splitlines(), 1):
        host, _, comment = raw.partition("#")
        host = host.strip().lower()
        if not host:
            continue
        match = REGION_TAG_RE.search(comment)
        if not match:
            # Letters-only compare, so REGION SCOPED / region_scoped / a case
            # slip are all caught rather than quietly ignored.
            if "regionscoped" in re.sub(r"[^a-z]", "", comment.lower()):
                raise ValueError(
                    f"{filename}:{lineno}: malformed region tag in {comment.strip()!r}; "
                    f"expected [REGION-SCOPED] or [REGION-SCOPED: cc cc ...]")
            continue
        first, dot, rest = host.partition(".")
        if not dot or not REGION_CODE_RE.match(first):
            raise ValueError(
                f"{filename}:{lineno}: [REGION-SCOPED] needs a two-letter first "
                f"label to substitute, got {host!r}")
        subset: tuple[str, ...] | None = None
        body = match.group(1).strip()
        if body:
            if not body.startswith(":"):
                raise ValueError(
                    f"{filename}:{lineno}: expected ':' before the code list in "
                    f"[REGION-SCOPED{body}]")
            subset = tuple(body[1:].split())
            bad = [c for c in subset if not REGION_CODE_RE.match(c)]
            if not subset or bad:
                raise ValueError(
                    f"{filename}:{lineno}: [REGION-SCOPED: ...] needs two-letter "
                    f"codes, got {bad or 'an empty list'}")
        patterns.setdefault(rest, subset)
    return patterns


def expand_regions(patterns: dict[str, tuple[str, ...] | None],
                   codes: dict[str, str] | list[str],
                   already: set[str]) -> list[str]:
    """Cross-product patterns x codes, minus names already present.

    A pattern's explicit subset is intersected with regions.txt, so a code
    listed in a tag but absent from regions.txt is never emitted.
    """
    out: set[str] = set()
    for pat, subset in patterns.items():
        use = [c for c in codes if subset is None or c in subset]
        out.update(f"{code}.{pat}" for code in use)
    return sorted(out - already)


COUNTRY_NOTE = (
    "# Note: {name} ({code}) only -- global entries plus this region's endpoints; "
    "other regions' are omitted. Regional endpoints are DNS-verified (they resolve "
    "to this region's LG infrastructure), not traffic-observed."
)


def scope_to_country(entries: list[str], own_pats: dict[str, tuple[str, ...] | None],
                     all_pats: dict[str, tuple[str, ...] | None],
                     code: str, codes: list[str]) -> list[str]:
    """Global entries with every region name stripped, plus this country's own.

    own_pats are the tier's tagged families; all_pats spans both tiers so a
    SAFE list does not retain STRICT's region names. A family whose explicit
    subset excludes this country is omitted entirely -- that is the whole point,
    since generating it would ship a name that NXDOMAINs here.
    """
    region_names = {f"{c}.{pat}" for pat in all_pats for c in codes}
    keep = {entry for entry in entries if entry not in region_names}
    mine = {f"{code}.{pat}" for pat, subset in own_pats.items()
            if subset is None or code in subset}
    return sorted(keep | mine)


def build_countries() -> int:
    """Write lists-regions/<cc>/ for every code in regions.txt. Returns count."""
    regions = parse_regions()
    if not regions:
        return 0
    safe = parse_src("safe.txt")
    strict_delta = parse_src("strict.txt")
    zones = parse_src("zones.txt")
    safe_pats = region_patterns("safe.txt")
    strict_pats = region_patterns("strict.txt")
    all_pats = {**safe_pats, **strict_pats}
    codes = list(regions)
    for code, name in regions.items():
        note = COUNTRY_NOTE.format(name=name, code=code)
        safe_cc = scope_to_country(safe, safe_pats, all_pats, code, codes)
        delta_cc = scope_to_country(strict_delta, strict_pats, all_pats, code, codes)
        outputs = {**compile_tier("safe", safe_cc, [], note),
                   **compile_tier("strict", safe_cc + delta_cc, zones, note)}
        out_dir = ROOT / "lists-regions" / code
        out_dir.mkdir(parents=True, exist_ok=True)
        for fname, content in sorted(outputs.items()):
            (out_dir / fname).write_text(content, encoding="utf-8", newline="\n")
        sums = [f"{hashlib.sha256((out_dir / f).read_bytes()).hexdigest()}  {f}"
                for f in sorted(outputs)]
        (out_dir / "SHA256SUMS").write_text(
            "\n".join(sums) + "\n", encoding="utf-8", newline="\n")
    return len(regions)


WILDCARD_HEADER = [
    "# Title: LG TV Blocklist ({tier}) — Pi-hole regex filters",
    "# Updated: {updated}",
    "# Entries: {n}",
    "#",
    "# PASTE THESE INTO PI-HOLE'S REGEX FILTERS, NOT AN ADLIST. Adlists accept",
    "# exact domains only and will silently ignore every line here.",
    "#   Pi-hole UI: Domains -> Add domain -> Regex  (or: pihole --regex '<line>')",
    "#",
    "# AdGuard Home / uBlock Origin users do NOT need this file: the",
    "# {tier}-adblock.txt list already has wildcard semantics via ||name^.",
    "#",
    "# Why this is so much shorter than {tier}-domains.txt: one regex per host",
    "# family replaces that family's entry for every country code, and keeps",
    "# working when LG adds a market this list has not enumerated yet.",
    "# ^[a-z][a-z]\\.family$ matches the two-letter region prefixes only; it",
    "# does NOT block the family apex or its other subdomains.",
    "#",
    "# Scope: these cover the region-prefixed hosts and the zone apexes. Keep",
    "# subscribing to {tier}-domains.txt for the specific audited hosts, which",
    "# have no wildcard equivalent.",
    LICENSE_LINE,
    "",
]


def apex_entries(entries: list[str]) -> list[str]:
    """Registrable apexes (two labels). No LG family uses a multi-part TLD."""
    return [entry for entry in entries if entry.count(".") == 1]


def cluster_stems(entries: list[str]) -> list[tuple[str, str]]:
    """(stem, separator) for datacentre-cluster hosts, e.g. eic.nudge.lgtvcommon.com.

    LG fronts these services from eic (Europe), aic (Americas) and kic (Korea).
    Region prefixes are two letters, so the ^[a-z][a-z]\\. regexes do not reach
    three-letter cluster names -- they need their own pattern or a SAFE wildcard
    user silently misses the cluster telemetry hosts entirely.
    """
    found: dict[tuple[str, str], None] = {}
    for entry in entries:
        match = CLUSTER_RE.match(entry)
        if match:
            found.setdefault((match.group(3), match.group(2)), None)
    return sorted(found)


def wildcard_lines(families: dict[str, tuple[str, ...] | None],
                   apexes: list[str],
                   clusters: list[tuple[str, str]] | None = None) -> list[str]:
    """Pi-hole regex filters: region prefixes, cluster prefixes, whole apexes.

    Anything already matched by an apex wildcard in this same file is skipped --
    in STRICT every family sits under a zones.txt apex, so its narrower regex
    would be dead weight behind a rule that matches the whole subtree.
    """
    apex_set = {apex.lower() for apex in apexes}

    def covered(host: str) -> bool:
        """True if an apex wildcard in this file already matches host."""
        return ".".join(host.split(".")[-2:]) in apex_set

    alt = "|".join(CLUSTER_PREFIXES)
    lines = [
        f"^[a-z][a-z]\\.{re.escape(fam)}$"
        for fam in sorted(families) if not covered(fam)
    ]
    # Region prefixes are 2 letters, so the pattern above cannot reach the
    # 3-letter datacentre clusters; without these a SAFE wildcard user silently
    # misses every cluster telemetry host, the ACR beacon included.
    lines += [
        f"^({alt})\\{sep}{re.escape(stem)}$"
        for stem, sep in (clusters or []) if not covered(stem)
    ]
    lines += [f"(\\.|^){re.escape(apex)}$" for apex in sorted(apex_set)]
    return lines


def compile_wildcard(tier: str, families: dict[str, tuple[str, ...] | None],
                     apexes: list[str],
                     clusters: list[tuple[str, str]] | None = None) -> str:
    lines = wildcard_lines(families, apexes, clusters)
    head = [row.format(tier=tier, updated=now_utc(), n=len(lines))
            for row in WILDCARD_HEADER]
    return "\n".join(head + lines) + "\n"


def make_headers(title: str, entries: int, note: str | None = None) -> list[str]:
    return [
        f"# Title: {title}",
        f"# Updated: {now_utc()}",
        f"# Entries: {entries}",
        *([note] if note else []),
        LICENSE_LINE,
        "",
    ]


def compile_tier(tier: str, domains: list[str], zones: list[str],
                 note: str | None = None) -> dict[str, str]:
    """Return output filename -> content for one tier."""
    if tier == "strict":
        domains = sorted(set(domains) | set(zones))
    title = f"LG TV Blocklist ({tier})"
    head = make_headers(title, len(domains), note)
    outputs: dict[str, str] = {}
    outputs[f"{tier}-domains.txt"] = "\n".join(head + domains) + "\n"
    outputs[f"{tier}-hosts.txt"] = "\n".join(
        head + [f"0.0.0.0 {d}" for d in domains]) + "\n"
    outputs[f"{tier}-adblock.txt"] = "\n".join(head + [f"||{d}^" for d in domains]) + "\n"
    return outputs


def flag(code: str) -> str:
    """Regional-indicator flag emoji for a two-letter country code."""
    return "".join(chr(0x1F1E6 + ord(ch) - ord("a")) for ch in code)


def country_table(regions: dict[str, str]) -> str:
    """Markdown table of copy-paste list URLs, one row per country."""
    rows = ["| Country | SAFE | STRICT |", "|---|---|---|"]
    for code, name in regions.items():
        cells = [
            " · ".join(
                f"[{fmt}]({RAW_BASE}/lists-regions/{code}/{tier}-{fmt}.txt)"
                for fmt in ("domains", "adblock", "hosts"))
            for tier in ("safe", "strict")
        ]
        rows.append(f"| {flag(code)} {name} `{code}` | {cells[0]} | {cells[1]} |")
    return "\n".join(rows)


def update_readme(regions: dict[str, str]) -> bool:
    """Rewrite README.md's generated country-link block; True if it changed."""
    if not regions or not README.is_file():
        return False
    text = README.read_text(encoding="utf-8")
    start, end = text.find(README_BEGIN), text.find(README_END)
    if start == -1 or end == -1 or end < start:
        raise ValueError(
            f"README.md needs the {README_BEGIN} and {README_END} markers, in that order")
    block = f"{README_BEGIN}\n\n{country_table(regions)}\n\n{README_END}"
    new = text[:start] + block + text[end + len(README_END):]
    if new == text:
        return False
    README.write_text(new, encoding="utf-8", newline="\n")
    return True


def load_all() -> tuple[list[str], list[str], list[str]]:
    safe = parse_src("safe.txt")
    strict_delta = parse_src("strict.txt")
    zones = parse_src("zones.txt")
    overlap = set(safe) & set(strict_delta)
    if overlap:
        raise ValueError(f"strict.txt duplicates safe.txt: {sorted(overlap)} (strict is a delta)")
    if set(zones) & set(safe):
        raise ValueError("zones.txt overlaps safe.txt — zones are strict-only")
    codes = parse_regions()
    if not codes:
        return safe, strict_delta, zones
    # Expand each tier's tagged families. Anything already hand-audited is
    # excluded, so an annotated entry always wins over its generated twin;
    # STRICT also excludes SAFE's names to keep the delta a real delta.
    safe_gen = expand_regions(region_patterns("safe.txt"), codes, set(safe))
    strict_gen = expand_regions(
        region_patterns("strict.txt"), codes,
        set(safe) | set(strict_delta) | set(safe_gen))
    return sorted(set(safe) | set(safe_gen)), sorted(set(strict_delta) | set(strict_gen)), zones


def generated_counts() -> tuple[int, int, int, int]:
    """Return (safe_generated, strict_generated, code_count, family_count)."""
    codes = parse_regions()
    if not codes:
        return 0, 0, 0, 0
    safe = parse_src("safe.txt")
    strict_delta = parse_src("strict.txt")
    safe_pats = region_patterns("safe.txt")
    strict_pats = region_patterns("strict.txt")
    safe_gen = expand_regions(safe_pats, codes, set(safe))
    strict_gen = expand_regions(
        strict_pats, codes, set(safe) | set(strict_delta) | set(safe_gen))
    return len(safe_gen), len(strict_gen), len(codes), len(safe_pats) + len(strict_pats)


def dry_run() -> dict[str, str]:
    safe, strict_delta, zones = load_all()
    safe_gen, strict_gen, n_codes, n_fams = generated_counts()
    all_outputs: dict[str, str] = {}
    safe_note = GENERATED_NOTE.format(n=safe_gen, codes=n_codes, fams=n_fams) if safe_gen else None
    strict_note = (GENERATED_NOTE.format(n=safe_gen + strict_gen, codes=n_codes, fams=n_fams)
                   if safe_gen + strict_gen else None)
    all_outputs.update(compile_tier("safe", safe, [], safe_note))
    all_outputs.update(compile_tier("strict", safe + strict_delta, zones, strict_note))
    # Wildcard/regex variants. SAFE wildcards only its own apexes -- never
    # zones.txt, whose apexes (lge.com, lgeapi.com, ...) carry the store,
    # updates and account login that SAFE exists to keep working.
    safe_pats = region_patterns("safe.txt")
    strict_pats = region_patterns("strict.txt")
    safe_apexes = apex_entries(parse_src("safe.txt"))
    all_outputs["safe-wildcard.txt"] = compile_wildcard(
        "safe", safe_pats, safe_apexes, cluster_stems(safe))
    all_outputs["strict-wildcard.txt"] = compile_wildcard(
        "strict", {**safe_pats, **strict_pats},
        safe_apexes + apex_entries(parse_src("strict.txt")) + zones,
        cluster_stems(safe + strict_delta))
    return all_outputs


def build() -> None:
    all_outputs = dry_run()
    LISTS.mkdir(exist_ok=True)
    for name, content in sorted(all_outputs.items()):
        (LISTS / name).write_text(content, encoding="utf-8", newline="\n")
    checksums = []
    for name in sorted(all_outputs):
        digest = hashlib.sha256((LISTS / name).read_bytes()).hexdigest()
        checksums.append(f"{digest}  {name}")
    # newline="\n": CRLF here breaks `sha256sum -c` on Windows checkouts.
    (LISTS / "SHA256SUMS").write_text(
        "\n".join(checksums) + "\n", encoding="utf-8", newline="\n")
    for name in sorted(all_outputs):
        print(f"wrote lists/{name}")
    n = build_countries()
    if n:
        print(f"wrote lists-regions/ for {n} countries")
    if update_readme(parse_regions()):
        print("wrote README.md country-link table")


def check() -> None:
    safe, strict_delta, zones = load_all()
    outputs = dry_run()
    safe_n = len(safe)
    strict_n = len(set(safe) | set(strict_delta) | set(zones))
    safe_gen, strict_gen, n_codes, n_fams = generated_counts()
    print(f"check OK: safe={safe_n} strict={strict_n} zone-anchors={len(zones)} "
          f"outputs={len(outputs)}")
    print(f"regions: {n_codes} codes x {n_fams} tagged families -> "
          f"{safe_gen} generated in safe, {strict_gen} more in strict "
          f"(audited: safe={safe_n - safe_gen} strict-delta={len(strict_delta) - strict_gen})")
    print(f"source files: {[p.name for p in sorted(SRC.glob('*.txt'))]}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Compile LG TV blocklists")
    parser.add_argument("mode", choices=["build", "check"], help="build writes lists/; check validates only")
    args = parser.parse_args(argv)
    try:
        if args.mode == "build":
            build()
        else:
            check()
    except (OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())